### ISSUE TITLE
Cache preload fields grayed out on the sub-site

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#105]
W3 total cache does not allow cache preload on a sub-site. Fields are greyed out.
Reference link: https://wordpress.org/support/topic/cache-preload-on-multisite-2/

**Comment by cssjoe** [comment]
This is a user setting issue.  In order to change the settings on subsites, the network admin must uncheck the general miscellaneous setting "Use single network configuration file for all sites." and save the settings.  The user must then go to the subsite dashboard and in the general settings click on the button that says "Use specific settings".  The user can then navigate to the Page Cache settings page to make changes.
![image](https://user-images.githubusercontent.com/11447263/83055842-69a56280-a022-11ea-9622-a4d74409e3d7.png)
![image](https://user-images.githubusercontent.com/11447263/83055892-7b870580-a022-11ea-81c9-27e5780bb5b5.png)
![image](https://user-images.githubusercontent.com/11447263/83055954-95284d00-a022-11ea-99d4-2ac1572a086d.png)
