### ISSUE TITLE
Add minify filter available for the file URLs

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#108]
Allow inserting placeholders for the version number (WP version for core files and theme version for custom files). Currently,  URLs need to be changed every time after  WP or theme is updated This would allow automating the process with a custom filter.

**Comment by alexanderaltendorfer** [comment]
I think this was closed by accident.  #267 does not address this issue, because the w3tc_minify_url_for_files filter allows only to filter the generated minify URL. This issue was about allowing the original file URLs (as entered in the minify settings) to be filtered, for example to insert a placeholder for plugin versions that frequently change.
