### ISSUE TITLE
Different Leverage Browser Caching results for Chrome and Firefox

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#144]
Image files are showing (expiration not specified) ing GTmerix Report using Google.
Different test results are when using Chrome
Chrome: https://gtmetrix.com/reports/www.amzrockstars.de/VseJHTSw
Firefox: https://gtmetrix.com/reports/www.amzrockstars.de/huDxD8xd

Reference topic: https://wordpress.org/support/topic/not-all-ressources-leverage-browser-caching/

**Comment by WPLibrary** [comment]
I think It’s an issue related to WebP rules that he/she added to htaccess file. Because Although the image extension is png or jpg, then they are going to see WebP images instead of png. It’s changing dynamically.

Here is the Chrome test that Marko ran:
![4CCD3C4A-DD24-4DFF-84B6-7D0C7A4E0BAE](https://user-images.githubusercontent.com/47054543/75439775-81117880-596b-11ea-897e-62ed31c57c0e.jpeg)


And Firefox test:
![7823D009-9521-4A79-A397-2F348F00B3C2](https://user-images.githubusercontent.com/47054543/75439817-92f31b80-596b-11ea-9c13-ea253da592f2.jpeg)


His/her server generates max-age directives based on MIME types. That’s why you see that warning. I think this is not a bug related to W3TC.

**Comment by mavas84** [comment]
Hello @WPLibrary 
Thank you for this information. I've missed this and just seen it myself.
Once again thank you for the information!
