### ISSUE TITLE
Add option not to remove Quotation marks when HTML minify is enabled

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#187]
HTML minify is removing Quotation marks when enabled. The HTML is valid and this feature makes page load even smaller, so faster and better for mobile visitors. Not all quotes are removed as HTML requires quotes when there's a space in the value.
But in some cases, it may impact the SEO
**the quotation mark missing from the description meta**
Disabling HTML minify resolves the issue.
https://wordpress.org/support/topic/quotation-marks-disapper-seriously-affecting-my-seo-rankings/

**Comment by cmchauhan17** [comment]
Due to the removal of quotation mark, there are these issues too

1) The description meta is not working, as the quotes from the description is stripped off, google is taking other lines from our articles as description, and sometimes even the footer’s contents.

2) It is effecting the preview in our WhatsApp, the image, as the quotes are stripped from the “og:image”.

3) It affected the AMP pages, I was getting some JSON codes in a preview of the link in WhatsApp.

It would be good if the quotes from the meta are not stripped.

**Comment by maxicus** [comment]
Recap:
`meta` tags are not parsed by browsers directly, but by apps, which seems do it violating W3C and fail to parse valid HTML without quotes.

WhatsApp is noted multiple times before acting bad in this case.

Google is not confirmed yet, even opposite - we have a lot of examples where meta tags don't have quotes and they are parsed well by google. There should be something else / more specific than just a quote for meta description tag.

It looks relevant trade-off in such situation to exclude `meta` tag from quotes removal optimization.
Negative effect is that websites with a lot of meta-tags, i.e. those implementing microdata and doing that meta-option way may have a lot of such. It's not so popular way at the moment.
