### ISSUE TITLE
Conflict with contact form 7 - need to disable and enable w3 cache to resolve issue

### ISSUE THREAD

**Issue by jitenit** [W3EDGE/w3-total-cache#226]
**I have updated latest  version of contact form 7 and then updated latest version of w3 cache** 

Contact Form 7 - Version 5.2 
W3 Total Cache - Version 0.14.2
Wordpress  - 5.4.2

**RED line after contact form 7 is coming in all form** 

Check image here for details 
[https://paste.pics/95ae0023a55819f427aae9c4c68b5e5c](url)

I face same issue in my 2-3 website

 - to resolve this i have clear cache and deactivate w3 total cache plugin and then again activate plugin and clear cache 

But this is not proper solution - can you please check this once

**Comment by mavas84** [comment]
Hello @jitenit 

First of all, thank you for taking the time to report this. I've tried to replicate the issue without success. Contact form ver 5.2, W3TC 0.14.2. I've tried different variations of the contact form. After the plugins are updated, it is necessary to purge the cache for some new files to take effect. So possibly this was just a minor glitch after you updated multiple plugins and as the CF is in elementor-widget-wrap there was a possible styling issue and rebuilding minify would help.
As the issue is resolved after the steps taken, this means that there is no actual conflict.
Thanks!
