### ISSUE TITLE
Twitter/FB do not load images/drop-in plugin compatible?

### ISSUE THREAD

**Issue by countrymouse** [W3EDGE/w3-total-cache#246]
I am a beginner in optimization and installed W3TC this week. I've now noticed that when I try to post links from my site to social media (Twitter and FB, specifically), the associated image with the post does not transfer over. 

The Twitter card verification came up with this error: 
"Unable to read card preview"

INFO:  Page fetched successfully
INFO:  5 metatags were found
ERROR: No card found (Card error)

I see that images could be blocked if W3TC is clashing with another plugin. I looked (inherited the site, did not build), and the only other cache plugin I can find are drop-in plugins:

"advanced-cache.php | Advanced caching plugin.
db.php | Custom database class.
object-cache.php | External object cache."

Other plugins include All in One SEO pack, All in One WP Security, Total Upkeep, MonsterInsights Analytics. Not sure if any of those would interfere. 

I had minify enabled but disabled it as a test - the images still do not load. 

Any help would be VERY much appreciated!!

**Comment by mavas84** [comment]
Hello @countrymouse 

Thank you for taking the time to report this issue and I am happy to assist you with this.
It seems like `<meta name="twitter:card" content="summary_large_image"/>` tag is missing. Potentially due to the HTML minification.
First, try disabling W3 Total Cache and see if the issue persists, and if the issue is still there, you need to add the mentioned meta tag.
After you've disabled minify for testing, have you purged the cache? If not please try disabling Minify in Performance>General settings and purge the cache. If the issue persits, disable the other settings one by one, save all settings, and purge the cache after each setting is disabled and see which one might be causing the issue. 

If you have Page cache, Object Cache and DB cache enabled, then advanced-cache.php,  db.php, and object-cache.php are all valid W3TC drop-ins.
