### ISSUE TITLE
Option to enforce trailing slash in disk enhanced

### ISSUE THREAD

**Issue by superpoincare** [W3EDGE/w3-total-cache#250]
By default Wordpress redirects urls without trailing slash to one with a trailing slash. 

However W3TC doesn't.

It's good to have the default behaviour. 

I understand this can create issues, but you could give an option to have it.

**Comment by mavas84** [comment]
Hello @vijayaraghavanramanan 

The reason this happens is that the page enhanced rules work with and without trailing slash. We don't know if the user wants the trailing slash or not. Also adding a rewrite rule in the Nginx or Apache config is tricky because we don't know which URLs should be the opposite. For example, the contact form 7 plugin doesn't work with a trailing slash, but we don't know if the user installed that plugin. Also, we don't know what plugins work with what rules and we don't want to have to add a million possibilities for each plugin there is.
It's tricky to make it work always.
there are wp-json requests, feeds, and similar that stops working with a slash.
However, we will consider adding the option for this.
Thanks!

**Comment by maxicus** [comment]
PHP fallback handles non-slash requests on envs with slash-terminated permalink structures. 
Should pass it to wp for redirect.

**Comment by Markshall** [comment]
Currently facing this problem myself.
It seems to enforce the trailing slash if:

1. you're using Disk: Basic for your page caching option, whether logged in or not
2. you're using Disk: Enhanced BUT only if you're logged in

I've had mine set at Disk: Enhanced and assumed it was working fine, but that was only because I was logged in. When I was logged out, it wasn't enforcing the trailing-slash for me. But using Disk: Basic enforces it either way.

From what I know, Disk: Basic invokes a PHP script to serve the static HTML file, where as Disk: Enhanced uses .htaccess rules to server the HTML file. So it must be that with Disk: Basic, we're processing PHP which can force a trailing slash redirect.

It would be great if there was a way to do this for Disk: Enhanced so we're not relying on PHP at all to serve static pages.

**Comment by dravnic** [comment]
Had a same issue. Wrote a specific htaccess RewriteRule for our website to enforce trailing slash. That works for our case, but it would be great if trailing slash enforce could be enabled in the plugin or that it is default as Wordpress handles trailing slash by itself and the plugin breaks this behaviour.

Here is one idea that could work for Disk: Enhanced mode and that shouldn't break any plugins/urls.

Trailing slash could be detected in the apache/nginx rewrite rules and enable a specific ENV variable that would be added to the RewriteRule path (e.g. `W3TC_TRAILING_SLASH=_slash`)

so the RewriteRule would like

`
 RewriteRule .* "/wp-content/cache/page_enhanced/%{HTTP_HOST}/%{REQUEST_URI}/_index%{ENV:W3TC_SSL}%{ENV:W3TC_PREVIEW}%{ENV:W3TC_TRAILING_SLASH}.html%{ENV:W3TC_ENC}" [L]
`
 
in the PHP trailing slash could be as well detected and add `_slash` to the cache file name.

so

`https://www.website.com/page/`
would be written on disk as
`page_enhanced/www.website.com/page/_index_ssl_slash.html`

and
`https://www.website.com/page`
would be written on disk as
`page_enhanced/www.website.com/page/_index_ssl.html`

If trailing slash is enabled in Wordpress the non-trailing slash page would be never cached and it would never hit its own cached version of the page (_index_ssl.html) as only trailing cache version would exist (_index_ssl_slash.html)
