### ISSUE TITLE
S3 metadata

### ISSUE THREAD

**Issue by jpb10** [W3EDGE/w3-total-cache#27]
Since June 2019, files uploaded to S3 have different metadata than before.

Older files:
```
Cache-Control 
Content-Type 
Expires
```

Newer files:
```
Content-Type	
x-amz-meta-access-control-allow-origin
x-amz-meta-content-type
x-amz-meta-last-modified
x-amz-meta-link
```

Which is problematic, because there are no expires or cache control values (for browser caching).

Also, the x-amz-meta-* values seem either redundant or unnecessary.

I suppose changes were made:
https://github.com/W3EDGE/w3-total-cache/commit/49dfa53324d1884796a910d27bf1647abd8227bf#diff-7971eb11690e9cb546b92abb2f8e6d63

**Comment by maxicus** [comment]
Cache-Control header is successfully returned by S3 at the time of issue creation. Code doing it:
https://github.com/W3EDGE/w3-total-cache/blob/master/CdnEngine_S3.php#L263

"Expires" header should not be copied to S3 since it's static afterwards. Max-age should be used (i.e. Cache-Control header).

Remaining handled by:
https://github.com/W3EDGE/w3-total-cache/commit/f9ef3871e5e66bd406a8675cd2adfa5b8fd593a9

x-amz are really useless. Removed.

CORS header can't be set by actual S3 API anymore, instead CORS policy should be set at bucket level. That's done now by "Create bucket" button.

**Comment by maxicus** [comment]
@seang96 
So now you should check why it's empty. At first make sure browsercache.enabled is true, that this is called:
```
			if ( $this->_config->get_boolean( 'browsercache.enabled' ) ) {
				$w3_plugin_browsercache = Dispatcher::component( 'BrowserCache_Plugin' );
				$cdn[0]->cache_config = $w3_plugin_browsercache->get_cache_config();
			}
```

and if so - go to `get_cache_config`. The only thing it does is reads configuration, so I guess you'll have some config options not set. checking it right in the code will show you which exactly.

**Comment by seang96** [comment]
@maxicus I found the issue.

Cdn_Core.php only sets the cache_config for $cdn[0], which in this case is set to CdnEngine_CloudFront.

https://github.com/W3EDGE/w3-total-cache/blob/ec453ed8758e705ce2475915398bc2419b13de09/Cdn_Core.php#L621-L624

CdnEngine_CloudFront uses CdnEngine_S3 in order to do the file uploads. When get_cdn is called it does not set the cache_config for CdnEngine_S3, since it creates an instance of CdnEngine_CloudFront.

https://github.com/W3EDGE/w3-total-cache/blob/ec453ed8758e705ce2475915398bc2419b13de09/CdnEngine_CloudFront.php#L15-L23

Please see my debug log which showed me what instance is created (CF) and the config it gets [debug.log](https://gist.github.com/seang96/85909db8e2463c1094dd22af8217cd12).

The simplest way to fix this that I think closely follows your design where get_cdn should be what makes any cdn instance:
1. Make S3 variable public in the instance, when in the switch statement and it is a CF it creates an S3 instance with the config and adds to the cdn array, and loop for each cdn to add cache_config to them all.
2. Instead of making the S3 variable public, add an s3 property to the config object  and inside of CdnEngine_CloudFront set the config property to the private s3 variable.
3. Design change, cache_config is sent with the $config in the constructor which would allow CdnEngine_CloudFront to set S3's cache_config.
4. CdnEngine_Base directly sets the $cache_config variable in the constructor. I suppose this would be a design change as well.

Which way would you like to proceed? I will make a PR for it as long as it doesn't take too many hours to do the change.

**Comment by maxicus** [comment]
Thanks for debugging.
So it was CloudFront engine, not pure S3.

Fixed by https://github.com/W3EDGE/w3-total-cache/commit/250ffb446b3f186ac59eb5980ee168caa6d52772 with some cleanup of those legacy code and performance optimization.
