### ISSUE TITLE
Whitespace around '<li>' needs to be preserved but removed

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [W3EDGE/w3-total-cache#273]
There's a bug in 

https://github.com/mrclay/minify/issues/643

which hasn't been fixed by them as they don't probably consider it a bug. 

But IMO, the whitespace inside `</li> <li` needs to be preserved. 

There are workarounds but it's better to fix it in HTML itself.

**Comment by mavas84** [comment]
Hello @vijayaraghavanramanan 

Thank you for taking the time to report this and to create the issue.
the devs are going to run the tests on this and we'll get back to you as soon as the tests are done.
Thanks!

**Comment by maxicus** [comment]
@vijayaraghavanramanan I agree with @picasticks that minify library should not remove spaces around display tags, otherwise we will end up with not removing it for any tag because someone used it as inline-block.

Unfortunately we don't live in ideal world and you are right - li is still often used in inline-block mode.
And considering it doesn't harm a lot, 2 bytes per quite rarely used tag, it's fine to add that workaround.
