### ISSUE TITLE
500 error when exporting config

### ISSUE THREAD

**Issue by aSanchezMontanez** [W3EDGE/w3-total-cache#304]
Hi, my w3tc returns a 500 error when i try to export the configuration:

[Sat Nov 21 16:35:51.948512 2020] [http:error] [pid 23170:tid 140476074149632] [client xxx.xxx.xxx.xxx:59452] AH02429: Response header name 'Disposici\xc3\xb3n de contenido' contains invalid characters, aborting request, referer: https://www.example.tld/wp-admin/admin.php?page=w3tc_general

Could you help me to solve this issue?

**Comment by mavas84** [comment]
Hello @aSanchezMontanez 

I am sorry about the issue you are experiencing, however, the issue is not related to W3 Total Cache but to your environment. 
What you can do is to back up the wp-content/w3tc-config/master.php which contains the configuration of the plugin. It's the same as exporting the configuration.
Thanks!
