### ISSUE TITLE
cli does not clear minify cache

### ISSUE THREAD

**Issue by Respheal** [W3EDGE/w3-total-cache#308]
These commands **do not work as stated.** The minify cache is not cleared.

```
[wordpress@server doc_root]$ wp w3-total-cache flush minify
Success: The minify cache is flushed successfully.
[wordpress@server doc_root]$ wp w3-total-cache flush all
Success: Everything flushed successfully.
```

----

**Steps to Replicate:**

1. Install WordPress: `wp core download`; `wp config create --dbname=$db --dbuser=$user --dbpass=$dbpass`
2. Install and activate W3TC: `wp plugin install w3-total-cache --activate`
3. Configure W3TC with the following commands:
```
wp w3-total-cache option set pgcache.cache.feed "true" --type="boolean"
wp w3-total-cache option set pgcache.enabled "true" --type="boolean"
wp w3-total-cache option set pgcache.engine "file" --type=string
wp w3-total-cache option set browsercache.cssjs.cache.control "true" --type="boolean"
wp w3-total-cache option set browsercache.cssjs.compression "true" --type="boolean"
wp w3-total-cache option set browsercache.cssjs.etag "true" --type="boolean"
wp w3-total-cache option set browsercache.cssjs.expires "true" --type="boolean"
wp w3-total-cache option set browsercache.cssjs.last_modified "true" --type="boolean"
wp w3-total-cache option set browsercache.enabled "true" --type="boolean"
wp w3-total-cache option set browsercache.html.cache.control "true" --type="boolean"
wp w3-total-cache option set browsercache.html.compression "true" --type="boolean"
wp w3-total-cache option set browsercache.html.etag "true" --type="boolean"
wp w3-total-cache option set browsercache.html.expires "true" --type="boolean"
wp w3-total-cache option set browsercache.html.last_modified "true" --type="boolean"
wp w3-total-cache option set browsercache.other.cache.control "true" --type="boolean"
wp w3-total-cache option set browsercache.other.compression "true" --type="boolean"
wp w3-total-cache option set browsercache.other.etag "true" --type="boolean"
wp w3-total-cache option set browsercache.other.expires "true" --type="boolean"
wp w3-total-cache option set browsercache.other.last_modified "true" --type="boolean"
wp w3-total-cache option set dbcache.enabled "true" --type="boolean"
wp w3-total-cache option set dbcache.engine "file" --type=string
wp w3-total-cache option set lazyload.enabled "true" --type="boolean"
wp w3-total-cache option set objectcache.enabled "true" --type="boolean"
wp w3-total-cache option set objectcache.engine "file" --type=string
wp w3-total-cache option set minify.auto "true" --type="boolean"
wp w3-total-cache option set minify.css.enable "true" --type="boolean"
wp w3-total-cache option set minify.css.engine "css" --type="string"
wp w3-total-cache option set minify.css.strip.comments "true" --type="boolean"
wp w3-total-cache option set minify.css.strip.crlf "true" --type="boolean"
wp w3-total-cache option set minify.enabled "true" --type="boolean"
wp w3-total-cache option set minify.error.notification "admin" --type="string"
wp w3-total-cache option set minify.html.enable "true" --type="boolean"
wp w3-total-cache option set minify.html.engine "html" --type="string"
wp w3-total-cache option set minify.html.strip.crlf "true" --type="boolean"
wp w3-total-cache option set settminify.js.enable "true" --type="boolean"
wp w3-total-cache option set minify.js.engine "js" --type="string"
```
4. Load site. CSS will not load due to minify cache.
5. Attempt to clear the cache: `wp w3-total-cache fix_environment apache; wp w3-total-cache flush all; wp w3-total-cache flush minify`
6. Load site again to check. CSS will not load due to minify cache.

**Comment by mavas84** [comment]
Hello @Respheal 

Thank you for taking the time to report this. 
Clearing the cache or clearing the minify cache will not resolve the CSS minify issue. If you are experiencing the issue when CSS minify is enabled, that means that some theme/plugin CSS files do not agree with being minified. So you should first make sure if the issue is with HTML Miinify, CSS minify or JS minify by disabling the options one by one in Performance>Minify, saving all settings, and purging the cache after each setting is disabled and see which option might be causing this.
Moving forward, if for example CSS minify is the issue, you need to check your console for any errors and exclude the specific file/files from being minified to avoid breaking the website.
Alternatively, you can use manual minify and add the JS and CSS files manually and in order, and checking the website after each file is added to minify to make sure the website is working as expected.
I hope this helps!
Thanks!

**Comment by Respheal** [comment]
Thanks for responding, but please note that per the provided replication steps, no extra plugins or themes were installed. This is with a fresh, vanilla installation of WordPress with nothing but the default twenty-twenty theme and W3TC installed.
> purging the cache after each setting is disabled

The issue is that  **`wp w3-total-cache flush` does not clear the cache.**

**Comment by mavas84** [comment]
Hello @Respheal 
Sorry for the late reply, 
You stated that minify Cache is not cleared and the website would not load due to minify cache. This indicates an issue with the minify option + the default twenty-twenty theme (noted in some cases). To test the behavior of $ wp w3-total-cache flush all disable minify and run $ wp w3-total-cache flush all
If the website is loading properly after that it means that the command works.
Thanks!

**Comment by Respheal** [comment]
To be more specific: **The command does not clear the minify cache.** Clearing the minify cache is the desired behavior. Flushing the cache should work when minify is enabled.

To prove this is not a theme-specific issue, I replicated the issue with the following popular themes:
- twentytwenty
- go
- opeanwp
- astra
- popularfx
- neve
- generatepress
- twentyseventeen
- twentysixteen
- twentynineteen

**Comment by mavas84** [comment]
Hello @Respheal 

Thank you for your patience and sorry for the late reply.
it took some time to make the tests for all provided themes. To confirm, W3TC minify does get cleared with the command. The file names are always the same in your case. SO for example Minified file is in wp-content/cache/minify/1615d.js which is not changed once the cache is purged. The filename remains the same only the content within the files is changed if for example some files are excluded from the minify.
I've checked this multiple times, Checked with the developers. The command works as expected.
Thanks!
