### ISSUE TITLE
Question about using Minio with w3-total-cache

### ISSUE THREAD

**Issue by NurdinDev** [W3EDGE/w3-total-cache#311]
I saw w3 total cache can be integrated with Amazon S3 and many other services to host static files, but is there a way to use Minio service instead?

**Comment by mavas84** [comment]
Hello @NurdinDev 
Thank you for your inquiry.
It has not been tested but as you can see in Performance>General settings under CDN type you can select Amazon Simple Storage Service (S3) Compatible. So you may want to try this option.
Again this has not been tested as there were no requests for this.
Thanks!

**Comment by watou** [comment]
@NurdinDev, please let us know if @mavas84's advice works for you, since the same advice applied to DigitalOcean Spaces (another S3 compatible storage provider which _has_ been requested), results in failure and lots of wasted time, and a bug report #243 left to die on the "Backlog" project.

**Comment by NurdinDev** [comment]
Hello, @mavas84  and @watou 

I've tried Amazon Simple Storage Service (S3) Compatible and I've added my configs but I got this error message
`Error: Unable to put object (S3Compatible::putObject(): [6] Could not resolve host:`

![Screen Shot 2020-12-16 at 12 07 42 PM](https://user-images.githubusercontent.com/5736522/102328132-bb4e1400-3f97-11eb-9f65-397e72a7be00.png)

- If I put `HTTPS` in my links I get the same error message, I tried both ways
- what should I use in the hostname field?
- what about the region, shouldn't have this option exist to select the region?

Thanks!

**Comment by watou** [comment]
Hi @NurdinDev, in "Replace site's hostname with" field, put the fully qualified hostname of where your CDN-uploaded files will be accessible over HTTPS.  So if a file on your website can be accessed with `https://www.mywebsite.com/logo.png` and after it's uploaded to the CDN it can also now be accessed at `https://mywebsitebucket.mycdn.com/logo.png`, put `mywebsitebucket.mycdn.com` in the "Replace site's hostname with" field.  No URL format in that field. Also check for extra spaces before or after entries in the other fields.

All that being said, owing to a bug in the plugin I get 411 errors against DigitalOcean Spaces with the test, and at some points in trying to use the plugin:

<img width="751" alt="Screenshot 2020-12-16 at 10 30 25" src="https://user-images.githubusercontent.com/3008217/102336939-beda9e80-3f89-11eb-9dc6-8fdfe1214b70.png">


(One has to admit it's a bug in the plugin, or otherwise one would have to say a major S3-compatible cloud storage provider isn't truly S3 compatible, which, no, don't.)

**Comment by juan131** [comment]
I can confirm that I was unable to use [MinIO](https://min.io) as CDN using the **"Amazon Simple Storage Service (S3) Compatible"** as CDN type.
