### ISSUE TITLE
CloudFront over S3 with Minify

### ISSUE THREAD

**Issue by unnamedfeeling** [W3EDGE/w3-total-cache#321]
Hey! Great work on plugin out there!
I have an issue with CloudFront over S3 with minify:
I have domains:

1. https://mysite.com - behind Cloudfront
2. https://mysite-alb.com - pointing directly at loadbalancer

I have configured all the behaviors at Cloudfront: 
- default (with max cacheability), 
- wp-admin (with min-cacheability) with origins pointing at mysite.com
- wp-includes, wp-content/uploads and wp-content/cache pointing at s3 bucket

Here's my problem:
When browser goes to mysite.com i will get only html and no assets (minified files) because they're not generated (there's no request done to the instance) - all minified css/js will return 404 because they're not in s3 bucket. Files will upload to s3 only after I do it manually. 

What have I tried so far:
- Read the manual https://github.com/W3EDGE/w3-total-cache/wiki/FAQ:-CDN 
- looking through the code
- implementing custom wp-cli functions to check cdn upload queue and upload files to s3 (those uploaded but had 0 length)
- tinkering with minification functions

Here are my questions:
1. How can I fix that issue?
2. Is it possible to generate those files without nginx rewrite at the point when the link is generated (or at some other point of time)?
3. What am I missing?

Thanks in advance!

PS: I have edited this issue because it was sent unfinished by error

**Comment by mavas84** [comment]
Hello @unnamedfeeling 

Thank you for your inquiry and I am happy to help.
In the kind of setup you are describing, w3tc doesn't have a trigger to generate minified files since you always ask only s3.
To remedy this, there are two things that you can do:
1. Use another domain for s3 content. in that case, w3tc uses its own domain initially, and once the content is generated, uploads it and starts to use the s3 domain.
2. (Recommended) use pull-type CDN instead of push-type, at least for minified content. i.e. CloudFront CDN. in that case CF will ask w3tc for content when it's not available there and it will be generated.

Thanks!

**Comment by unnamedfeeling** [comment]
A greater way of sorting this out is cloudfront origin groups. 
I have created a group with primary origin for s3 and secondary for container. Then wordpress was reconfigured (check if wordpress is accessed by container domain name instead of main one) to listen to 2 domain names and it works)
Thanks
