### ISSUE TITLE
Mimetype "application/x-javascript" for .js files?

### ISSUE THREAD

**Issue by cjsinnbeck** [W3EDGE/w3-total-cache#339]
Hi,

W3TC serves javascript files with ".js" extension as mimetype `application/x-javascript`, whereas files with ".js2" extension is served as `application/javascript`. This is configured in the file **inc/mime/cssjs.php**, where it says:

```
<?php

/**
 * CSS and JS mime types
 */
return array(
	'css' => 'text/css',
	'htc' => 'text/x-component',
	'less' => 'text/css',
	//JS - varieties
	'js' => 'application/x-javascript',
	'js2' => 'application/javascript',
	'js3' => 'text/javascript',
	'js4' => 'text/x-js',
);
```

I am wondering if it should not be the other way around - isn't `application/javascript` the standard mimetype for .js files now?

Thanks,

**Comment by mavas84** [comment]
Hello @cjsinnbeck 

Thank you for your inquiry and I am happy to answer.
As you can see in the provided code, those are varieties of the mime types that may be set. This depends on the environment and the encoding of those files. application/x-javascript was experimental (hence the x- prefix) for a transitional period until application/javascript could be standardized.
As far a browsers are concerned, there is no difference (at least in HTTP headers). This was just a change so that the text/* and application/* MIME type groups had a consistent meaning where possible. (text/* MIME types are intended for human-readable content, JavaScript is not designed to directly convey meaning to humans).
Thanks!

**Comment by cjsinnbeck** [comment]
Thank you @mavas84. 

I am aware that most browsers currently treat application/x-javascript correctly. So this is no big problem, of course.

My reason for asking is that the RFC states that use of the experimental types are “discouraged”. I have come across one “site scanner” that checks if various headers like CSP, HSTS, X-Frame-Options, etc, are present. It also flagged the application/x-javascript as an obsolete/bad content-type while crawling the site I checked.

I know that this is of course anecdotal and not very significant, but I was just wondering if there was a specific reason for the ordering of the mimetypes. Why not associate the RFC standard “application/javascript” with the most common file extension (.js), and then move “application/x-javascript” to .js2?

Thanks for a really great plugin.

**Comment by mavas84** [comment]
Hello @cjsinnbeck 

Thank you for your feedback.
Nop particular reason besides historical. You may try changing the order but as I've mentioned it depends on the environment and the encoding of those files.
Thanks!
