### ISSUE TITLE
memcached issue with php-fpm after 0.10 update

### ISSUE THREAD

**Issue by Hasan0ff** [W3EDGE/w3-total-cache#35]
Hi, this happened after the last update.

I'm using php 7.3.9 with memcached. The web system compromises of nginx+php-fpm+mariadb (centos 7). I gotta say total cache is a life saver when it comes to websites with 2k+ users online. I use memcached for page, database and object caching via w3tc.

Yesterday, I saw w3tc update and I clicked it. Afterwards, the nightmare began. First, I thought everything was related to latest wordpress update. But, afterwards checked the php-fpm and none of the php-fpm children terminated.

There were 2 updates yesterday for me. One wordpress core update and the other w3tc. So the culprit was one of the two.

At max traffic, we get like 8-20 php-fpm children serving everything. However, php-fpm kept adding children and when maxed out the website would get slower and slower. I removed w3tc and changed the php-fpm to 7.2.2 and restart nginx and php-fpm. The website began to work smoothly.

I went to wordpress.org (https://wordpress.org/plugins/w3-total-cache/advanced/) and downloaded 0.9.7.5. Set up everything as previously (nginx settings and php-fpm 7.3.9) and voila everything works perfectly again.

Sorry for the long rant but it seems that the memcached binary logging settings in the latest update has a bug. Please do fix it if you deem the problem to be of importance.

**Comment by cprivite** [comment]
Can confirm, I also use nginx+php-fpm and upgrading to w3tc 0.10 tanked our site performance. As soon as I disable w3tc everything is great again.

**Comment by maxicus** [comment]
Please comment out the line https://github.com/W3EDGE/w3-total-cache/blob/master/Cache_Memcached.php#L63

that sets up binary protocol when available and let me know if that's the root of the problem.
Potentially it doesn't work in your stack well.

**Comment by dlsumy** [comment]
> Hi, this happened after the last update.
 
> Sorry for the long rant but it seems that the memcached binary logging settings in the latest update has a bug. Please do fix it if you deem the problem to be of importance.

I confirm. Same problems with memcache

**Comment by cprivite** [comment]
@maxicus I'll give this a go later tonight and report on findings.

**Comment by novazembla** [comment]
Hello! I've just experienced the same issue. 

After the update to 0.10 the side started to crawl. Switching Object Cache from MemCached to APC/APCu brought it back to speed. 

Commenting https://github.com/W3EDGE/w3-total-cache/blob/master/Cache_Memcached.php#L63 out did bring it back to speed. 

Would there a way to make this line optional? 

Thank you!

**Comment by maxicus** [comment]
Official docs claim binary protocol should be always faster, but reality seems different on some environments.

other people report similar issues with binary protocol:
https://grokbase.com/t/danga/memcached/0834m4qkmd/the-write-strategy-of-the-client-implement-affects-the-set-performance-dramatically
https://github.com/php-memcached-dev/php-memcached/issues/24

For those who experience that, does adding 
$this->_memcache->setOption( \Memcached::OPT_TCP_NODELAY, true );
instead of commenting out binary protocol help too?

**Comment by maxicus** [comment]
Here is the fix to try on stacks with described problem https://github.com/W3EDGE/w3-total-cache/commit/3833a672ae076794f6de7ce5ed2fccf3291ba51e

**Comment by novazembla** [comment]
Can confirm that adding `$this->_memcache->setOption( \Memcached::OPT_TCP_NODELAY, true );` did indeed also solve the problem.

**Comment by cprivite** [comment]
> Here is the fix to try on stacks with described problem [3833a67](https://github.com/W3EDGE/w3-total-cache/commit/3833a672ae076794f6de7ce5ed2fccf3291ba51e)

Can confirm this worked for me too.

**Comment by dlsumy** [comment]
> Here is the fix to try on stacks with described problem [3833a67](https://github.com/W3EDGE/w3-total-cache/commit/3833a672ae076794f6de7ce5ed2fccf3291ba51e)

Great! It works! Thanks!

**Comment by zehferrari** [comment]
> Here is the fix to try on stacks with described problem [3833a67](https://github.com/W3EDGE/w3-total-cache/commit/3833a672ae076794f6de7ce5ed2fccf3291ba51e)

I'm not sure why but this approach did not solve the problem for me.
I'd to rollback the file to its previous version: https://github.com/W3EDGE/w3-total-cache/commit/647eaebe7ae909b2807f2c95973fe9d7b63bf640

**Comment by maxicus** [comment]
Thanks everyone for testing. 
Merged to master. Patch release will be issued shortly.

**Comment by archon810** [comment]
I was doing some low-level profiling out of curiosity and here are my results of updating a single post, which causes over 3000 `delete` and `get` requests to memcached because each url has 48 caches (see this for an example https://gist.github.com/704febfaa3576c45bba101ad9e9894ee), and there are 71 urls in `$this->queued_urls` for us (or double that if you enable the W3TC AMP plugin). 

That's 3400 `get` and `delete` requests, which even with memcached being as fast as it is, could take multiple seconds.

The effect of not setting `$this->_memcache->setOption( \Memcached::OPT_TCP_NODELAY, true );` is huge.

Not set:
![image](https://user-images.githubusercontent.com/469543/64888218-3d29f180-d61f-11e9-8aa6-73b2e86ea033.png)

Set:
![image](https://user-images.githubusercontent.com/469543/64887731-1fa85800-d61e-11e9-9fb0-40676fa4d44c.png)

No wonder 0.10.0 brought down so many sites. Just thought people would be curious to see some data.
