### ISSUE TITLE
Stop Press!

### ISSUE THREAD

**Issue by superpoincare** [W3EDGE/w3-total-cache#360]
I used the github repo for testing. Downloaded the zip and uploaded the file and activated it (on a test site). 

I was able to active it but good this immediately. 
![image](https://user-images.githubusercontent.com/13736892/113436311-1bab7900-9402-11eb-872f-42bc29d1b6ce.png)

On the BoldGrid test site for Wordpress, it wouldn't even activate and crash the site.

**Comment by cssjoe** [comment]
The issue is due to the GitHub ZIP file using a different plugin folder name.  You can rename the folder that is extracted (to "w3-total-cache") and activate the plugin.  You can use the ZIP file that was uploaded to releases, which has the correct folder name: https://github.com/W3EDGE/w3-total-cache/releases/download/2.1.1/w3-total-cache.2.1.1.zip
