### ISSUE TITLE
Preconfigure memcached caching 

### ISSUE THREAD

**Issue by lukasmrtvy** [W3EDGE/w3-total-cache#405]
I am using configuration:
```
  define( 'WP_CACHE', true );
  define( 'W3TC_CONFIG_DATABASE', true );
  define( 'W3TC_CONFIG_CACHE_ENGINE', 'memcached' );
  define( 'W3TC_CONFIG_CACHE_MEMCACHED_SERVERS', 'custom-memcached-host:11211' );
```
directly in `wp-config.php`, but W3TC is still unconfigured..

Any idea? Or possibilty to configure at least connection parameters from env variables? ( its not possible to set custom memcached server from webui )

Thanks

**Comment by mavas84** [comment]
Hello @lukasmrtvy 
define( 'W3TC_CONFIG_DATABASE', true ); is used to store plugin configuration in a database instead of file.
ou should note that many types of requests can be made prior to the initialization of the database, so switching to database-stored configuration will increase request response time. This functionality should be used only when you have no other option. To enable database-stored setting, add define( 'W3TC_CONFIG_DATABASE', true ); to your wp-config.php and the plugin will immediately begin to use options table for configuration storage via wp-options table. Alternatively, W3TC_CONFIG_DATABASE_TABLE constant can be defined to specify a table you created specifically for this use case.

Note: If you customized your settings prior to switching to the database storage setting, you will lose your configuration settings. Be sure to export settings beforehand, then import afterward. You can then remove configuration file from your source control if it was there and delete it. Ideally, defining the W3TC_CONFIG_DATABASE constant prior plugin activation allows you to skip all of these steps.
Also, W3TC recognizes PHP modules so you need to install phpmemcached
https://github.com/W3EDGE/w3-total-cache/wiki/FAQ:-Installation:-Memcached-Server
Thanks!
