### ISSUE TITLE
Physical robots.txt file from W3CT is overriding rules from all other plugins

### ISSUE THREAD

**Issue by arnaudbroes** [W3EDGE/w3-total-cache#420]
Your latest update to W3 Total Cache is really messing things up for every other plugin that modifies the robots.txt file. You are forcefully generating a physical robots.txt file to disallow access to your cache directory, which means that rules from other plugins are overridden and ignored.

You should use the https://developer.wordpress.org/reference/hooks/wp_robots/ filter hook to add your disallow directive so that you do not affect other plugins. Hopefully this is something you'd be able to address relatively soon as many plugin teams, including ours, are seeing a large increase in support tickets because of this conflict.

Steps to reproduce:

1. Install the latest version of All in One SEO and W3 Total Cache 2.7.1.
2. Go to AIOSEO > Tools > Robots.txt. You'll see a warning there because AIOSEO detected a physical file.
3. Remove the physical file via AIOSEO and add a few robots.txt rules via AIOSEO. Save changes.
4. Wait a few minutes. W3CT will have regenerated their physical robots.txt file, overriding the directives in AIOSEO.

**Comment by mavas84** [comment]
Hello @arnaudbroes 

Thank you for taking the time to open this ticket.
We are aware of the issue as it was reported numerous times. We are working on a fix and this will be patched soon.
Thanks!
Reference topics:
https://wordpress.org/support/topic/w3tc-conflict-with-aioseo/
https://wordpress.org/support/topic/message-error-robot-txt/
https://wordpress.org/support/topic/robot-disallow/
https://wordpress.org/support/topic/robots-txt-cache-directory/
https://wordpress.org/support/topic/blocked-cache-directory-from-google-bots-triggering-mobile-friendliness-issue/
https://wordpress.org/support/topic/robots-txt-error/

**Comment by MediaMaquina** [comment]
Why would you add a disallow rule to the cache directory?
Search engines cannot render the page correctly without the css inside of it. Don't do that!

**Comment by ucsendre** [comment]
I can not understand why does it take so long to fix such a stupid error. How the hell could someone do such a weird thing as to disallow cache to being crawled?

**Comment by yogster** [comment]
I've had to disable W3TC until this gets fixed - I get a massive performance hit, but Google is reporting my site as not mobile-friendly and I can't afford the impact this will have in our rankings. I'll have to look at a different caching solution if this doesn't get fixed very soon.

**Comment by ucsendre** [comment]
I have deleted W3TC crap from robots.txt file and set file permissions to 444 until this 💩 get fixed.

**Comment by mavas84** [comment]
Hello everyone.
Thank you for taking the time and post a comment on this. 
We are sorry about the inconvenience and we are working on a fix for this.
you can install the WP rollback plugin and revert to the previous version of the plugin.
The files that were changed are:
Generic_Environment.php
Util_Rule.php
w3-total-cache-api.php
So you can download the previous version from [here](https://downloads.wordpress.org/plugin/w3-total-cache.2.1.6.zip) and replace the files that were changed.
Thank you for your patience!

**Comment by KZeni** [comment]
I personally have write permissions on the base-level website directory disabled (even for the web server process itself as I have a managed WP update solution.) As such, I suppose I (and others that also have their permissions hardened) can consider this a temporary inconvenience to have that file permissions warning shown until an update is released where that should just go away (per it no longer wanting to create a physical robots.txt file & instead uses what WP plugins should use [the virtual robots.txt WP has that allows for others to make adjustments to it via official hooks.]) So no action is needed (just ignore the warning) and then just update to the fixed version when it's available for those with these permissions.

**Comment by KZeni** [comment]
For sites/hosting where that physical file was created, is the updated version going to delete the robots.txt file it created, or is manual deletion going to be necessary even after updating?

If it is going to automatically delete the file it created (certainly would be nice), it might be advisable to have it check the contents of the file to see if it matches what it originally created before deleting. While this isn't the case for my setup, I'm thinking there might be sites out there that manually manage their robots.txt file as a physical file (rather than using a virtual robots.txt plugin [or similar] to make adjustments to the virtual one as needed) and might be a bit thrown off to find W3TC deleted the file they intentionally want on the site with their possible customizations (while it then makes sense to delete it automatically if it only contains what W3TC added.)

Similarly, if this looked to edit an existing robots.txt file, it should probably look to remove what it added while keeping the rest of the physical robots.txt file as-is.

Again, the virtual robots.txt file should be what's used for all sites, but this cleanup may need to take these various situations into account to fix things properly for everyone (without requiring manual interaction to complete.)
