### ISSUE TITLE
Image Service and WP_Filesystem API.

### ISSUE THREAD

**Issue by mavas84** [W3EDGE/w3-total-cache#460]
Image Service extension now working correctly with WP_Filesystem API.
The extension requests to use WP_Filesystem API, but does not check the returned answer as to whether it can be used or not… it just carries on and attempts, resulting in a fatal error in the case where the answer from WordPress was “you can’t use this at this point”. 
Reference topic: https://wordpress.org/support/topic/w3tc-image-service/

**Comment by zjagust** [comment]
Since I'm using the SSH method regarding access to WP Filesystem, I think there should be credentials check somewhere in your code in the case where the default method is not accepted. Something like this maybe:

```
if ( ! WP_Filesystem($creds) ) {
    // our credentials were no good, ask the user for them again
    request_filesystem_credentials($url, $method, true, false, $form_fields);
    return true;
    }
```

I'm not a developer/programer, so I apologize if my assumption is incorrect. Thank you!
