### ISSUE TITLE
redis enabled but not used

### ISSUE THREAD

**Issue by jyjohnson** [W3EDGE/w3-total-cache#479]
I have WP running on EC2 with Redis running on Elasticache. After installing php redis, the W3 extension test shows redis is enabled. I then enabled Object Cache and Page Cache using redis, and enabled debug mode (I also restarted apache). Both the elasticache metrics and the debug output show no actual data is stored in redis: 

Performance optimized by W3 Total Cache. Learn more: https://www.boldgrid.com/w3-total-cache/
--
  |  
  | Object Caching 0/387 objects using redis
  |  
  | Object Cache debug info:
  | Caching:            enabled
  | Total calls:        387
  | Cache hits:         0
  | Total time:         0.1029
  | Page Caching using redis (Requested URI contains query)
  |  
  | Page cache debug info:
  | Engine:             redis
  | Cache key:
  | Creation Time:      1642003184.000s
  | Header info:
  | X-Powered-By:       PHP/7.4.21
  | Content-Type:       text/html; charset=UTF-8

Note that by default Elasticache does not use authentication, so I commented out the REDIS_PASSWORD line in db-config.php. Any ideas?

**Comment by mavas84** [comment]
Hello @jyjohnson 

Thank you for reaching out and I am happy to assist you with this. 
As for Page Caching as you can see there is a note: Requested URI contains the query. This means that possibly the option  Cache URIs with query string variables is not enabled in Performance>Page Cache and therefore the page is not cached since W3 Total Cache does not cache URLs with query strings by default.
As for Object Caching, I am not quite sure why there are no hits. Can you please share the URL of the page you are referring to?
Also, Github is not a support platform, so it would be great if you can drop us a note directly via the plugin in Performance>Support if you are not comfortable sharing the URL in public.
Thanks!
