### ISSUE TITLE
Impossible to enable SSL with an S3Compatible provider

### ISSUE THREAD

**Issue by zcourts** [W3EDGE/w3-total-cache#492]
In the UI it has "SSL Support" but even when this is set to always use SSL an S3Compatible host is connected to on port 80 and without SSL.

Looking at the code I can see the 3rd parameter is always set to false https://github.com/W3EDGE/w3-total-cache/blob/6669102996cbef3e5dd9ae453003206390477f03/CdnEngine_S3_Compatible.php#L34
That 3rd parameter is the useSSL option https://github.com/W3EDGE/w3-total-cache/blob/master/lib/S3Compatible.php#L200

This is later used on line https://github.com/W3EDGE/w3-total-cache/blob/master/lib/S3Compatible.php#L962
and https://github.com/W3EDGE/w3-total-cache/blob/master/lib/S3Compatible.php#L970
but since this is hard coded to always be false, these will never be tree.

Add an option to pass this param through or pass it through as true if SSL is set to always enabled.
FYI we have a pro license and would really like a fix upstream. For now we hard coded `https` and `true` on the two lines above to make it work but obviously any update can replace this and break things so an upstream fix is ideal.

**Comment by mavas84** [comment]
Hello @zcourts 

Thank you for reaching out.
We are aware of the problem with the S3 COmpatible CDN type. It has been reported previously in this ticket:
https://github.com/W3EDGE/w3-total-cache/issues/243
The problem is that the library is very old and in order to update it, we'll have to update a lot of code outside of the library.
Please make sure to add your comment to the issue provided so we can keep the problem in one place.
Thanks!
